### ISSUE TITLE
Issue on checkout page

### ISSUE THREAD

**Issue by james-radweb** [bobbyshaw/magento-footer-js#1]
Nice extension and seems to work well but when we get to the checkout page we get lots of JS errors using Chrome. We are using Magento 1.7.0.2 and tested using the default theme with no other extensions installed.

Prototype is loaded before opcheckout.js so unsure why the errors are appearing.

Uncaught ReferenceError: Billing is not defined (index):690
Uncaught ReferenceError: Shipping is not defined (index):716
Uncaught ReferenceError: ShippingMethod is not defined (index):797
Uncaught ReferenceError: payment is not defined (index):801
Uncaught ReferenceError: Payment is not defined (index):807
Uncaught TypeError: Cannot set property 'currentMethod' of undefined 

Any ideas?

**Comment by james-radweb** [comment]
Further to this I moved opcheckout.js to the head using XML and removed it from the onepage.phtml and it has removed most errors but still get one error which prevents moving through the checkout:

Uncaught ReferenceError: payment is not defined 

Is there anyway to prevent this extension from running on the checkout page?

**Comment by langos** [comment]
I have the following error on the checkout page:

Fatal error: Call to a member function getBlock() on a non-object in ....\app\code\community\Meanbee\Footerjs\Model\Observer.php on line 17

**Comment by bobbyshaw** [comment]
New implementation on master for you to try out.
