### ISSUE TITLE
Scripts skipped by module

### ISSUE THREAD

**Issue by lhall-amphibee** [bobbyshaw/magento-footer-js#17]
Hi,

I have a problem with version 0.1.0, which seems to skip external scripts.

`<script type="text/javascript" src="script.js"></script>` is skipped, while `<script type="text/javascript">var h = 'Hello World';</script>` is moved to the bottom.

Using files of the version 0.0.5 works.

This was tested on a Magento 1.7.0.2 & 1.9.2.4.

Thanks for your work.

**Comment by bobbyshaw** [comment]
Thanks for the report, I will investigate later this week.

**Comment by lhall-amphibee** [comment]
If you want to have a look, this fix the problem : https://github.com/lhall-adexos/magento-footer-js/commit/b8ebf1f940906b70a8c74747673d4d9b08d92620

I have not tested it thoroughly though, so I didn't make a pull request.

**Comment by RidRack** [comment]
Hi, 

I've tested the changes and they work fine. I've made a pull request with them in. Good spot @lhall-adexos. 

https://github.com/bobbyshaw/magento-footer-js/pull/18

**Comment by lhall-amphibee** [comment]
Thanks for the testing !

**Comment by bobbyshaw** [comment]
Published new release with this fix https://github.com/bobbyshaw/magento-footer-js/releases/tag/v0.1.1.  Thanks both.
