### ISSUE TITLE
Magento crashed when I activated this module

### ISSUE THREAD

**Issue by salvocolonna** [bobbyshaw/magento-footer-js#20]
Hi, I've tested your module but my Magento 1.9.2 has gone down.
Hope this report should help anyone:

`a:5:{i:0;s:71:"Mage registry key "_singleton/meanbee_footerjs/observer" already exists";i:1;s:3837:"#0 /var/www/vhosts/domain.it/httpdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /var/www/vhosts/domain.it/httpdocs/app/Mage.php(477): Mage::register('_singleton/mean...', false)
#2 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(22123): Mage::getSingleton('meanbee_footerj...')
#3 /var/www/vhosts/domain.it/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('core_block_abst...', Array)
#4 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2641): Mage::dispatchEvent('core_block_abst...', Array)
#5 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2335): Mage_Core_Block_Abstract->toHtml()
#6 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2275): Mage_Core_Block_Abstract->_getChildHtml('optional_zip_co...', true)
#7 /var/www/vhosts/domain.it/httpdocs/app/design/frontend/smartwave/porto/template/page/html/head.phtml(38): Mage_Core_Block_Abstract->getChildHtml()
#8 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3428): include('/var/www/vhosts...')
#9 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3459): Mage_Core_Block_Template->fetchView('frontend/smartw...')
#10 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3473): Mage_Core_Block_Template->renderView()
#11 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2617): Mage_Core_Block_Template->_toHtml()
#12 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2335): Mage_Core_Block_Abstract->toHtml()
#13 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2279): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#14 /var/www/vhosts/domain.it/httpdocs/app/design/frontend/smartwave/porto/template/page/1column.phtml(35): Mage_Core_Block_Abstract->getChildHtml('head')
#15 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3428): include('/var/www/vhosts...')
#16 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3459): Mage_Core_Block_Template->fetchView('frontend/smartw...')
#17 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(3473): Mage_Core_Block_Template->renderView()
#18 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(2617): Mage_Core_Block_Template->_toHtml()
#19 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(28684): Mage_Core_Block_Abstract->toHtml()
#20 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(14234): Mage_Core_Model_Layout->getOutput()
#21 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(11585): Mage_Core_Controller_Varien_Action->renderLayout()
#22 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(11500): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'home')
#23 /var/www/vhosts/domain.it/httpdocs/app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'home')
#24 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(14262): Mage_Cms_IndexController->indexAction()
#25 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(18726): Mage_Core_Controller_Varien_Action->dispatch('index')
#26 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(18256): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /var/www/vhosts/domain.it/httpdocs/includes/src/__default.php(21152): Mage_Core_Controller_Varien_Front->dispatch()
#28 /var/www/vhosts/domain.it/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#29 /var/www/vhosts/domain.it/httpdocs/index.php(83): Mage::run('', 'store')
#30 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"it";}`

**Comment by bobbyshaw** [comment]
You're using Magento's compilation which isn't really recommended any more.
You'll either need to turn it off or recompile. Then flush cache for good
measure and you'll be on your way.

**Comment by salvocolonna** [comment]
Thank you! Disabling compilation it worked. But after moving javascript to the footer my homepage no longer load any script then I have now most of page blank.
I paste below some lines that may help you 

`<script type="text/javascript">// <![CDATA[
		jQuery(function($){
			$("#latest_product .filter-products .owl-carousel").owlCarousel({lazyLoad: true,    itemsCustom: [ [0, 1], [320, 1], [480, 2], [768, 3], [992, 4], [1200, 5] ],    responsiveRefreshRate: 50,    slideSpeed: 200,    paginationSpeed: 500,    scrollPerPage: false,    stopOnHover: true,    rewindNav: true,    rewindSpeed: 600,    pagination: false,    navigation: false,    autoPlay: true,    navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]});
		});
		
// ]]>
</script>`

` <script>
    jQuery(function($){
        $("#brands-slider-demo-9").owlCarousel({
            lazyLoad: true,
            itemsCustom: [ [0, 1], [320, 1], [480, 2], [640, 3], [768, 4], [992, 5], [1200, 6] ],
            responsiveRefreshRate: 50,
            slideSpeed: 200,
            paginationSpeed: 500,
            scrollPerPage: false,
            stopOnHover: true,
            rewindNav: true,
            rewindSpeed: 600,
            pagination: false,
            navigation: true,
            autoPlay: true,
            navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]
        });
    });
    </script>`

`<script type="text/javascript">// <![CDATA[
		jQuery(function($){
			$("#latest_news .owl-carousel").owlCarousel({
				lazyLoad: true,
				itemsCustom: [ [0, 1], [320, 1], [480, 1], [640, 2], [768, 2], [992, 2], [1200, 2] ],
				responsiveRefreshRate: 50,
				slideSpeed: 200,
				paginationSpeed: 500,
				scrollPerPage: false,
				stopOnHover: true,
				rewindNav: true,
				rewindSpeed: 600,
				pagination: false,
				navigation: true,
				autoPlay: true,
				navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]
			});
		});
		
// ]]></script>`

**Comment by bobbyshaw** [comment]
Hi @coolbeat8885, it's difficult for me to debug this. Is this javascript previously on the homepage but after installation it's missing from the page completely or it's at the bottom but become non-functional?

You could try remove the //CDATA as this shouldn't be needed anymore just in case that's causing an issue.

**Comment by salvocolonna** [comment]
Removing CDATA I don't solve this issue. It' s a big problem because I can't revert it to the previous configuration, neither restoring backup of httpdocs folder.
If you are so kind that you can contact me privately I will provide you the url of website

**Comment by bobbyshaw** [comment]
I can't provide production support, sorry. Why can't you remove or disable the extension?

**Comment by salvocolonna** [comment]
Ok, no problem.
From firefox debug console I have found a problem:
Unreachable code after return statement > ea0e99b8856231a8314e4d63b432c44e.js
May be this script that blocks load page correctly?
Into this file is contained a Prototype script with this header:

/*  Prototype JavaScript framework, version 1.7
 *  (c) 2005-2010 Sam Stephenson
 *
 *  Prototype is freely distributable under the terms of an MIT-style license.
 *  For details, see the Prototype web site: http://www.prototypejs.org/
 *
 *--------------------------------------------------------------------------*/

var Prototype = {

  Version: '1.7',

  Browser: (function(){
    var ua = navigator.userAgent;
    var isOpera = Object.prototype.toString.call(window.opera) == '[object Opera]';
    return {
      IE:             !!window.attachEvent && !isOpera,
      Opera:          isOpera,
      WebKit:         ua.indexOf('AppleWebKit/') > -1,
      Gecko:          ua.indexOf('Gecko') > -1 && ua.indexOf('KHTML') === -1,
      MobileSafari:   /Apple.*Mobile/.test(ua)
    }

**Comment by salvocolonna** [comment]
SOLVED!
I'm very sorry to have bothered you, this problem was caused by Flat catalog, in exception log I noticed that magento was not able to access to a table in the database, then I disabled flat catalog and all is back right.
Anyway your support was crucial. Thank you again!

**Comment by bobbyshaw** [comment]
Hmm, that is a strange one. You do want flat catalog to work really because it's more performant. 

It looks like you had javascript merging on. If you disable temporarily, you might be able to see exactly where the issue in the JavaScript lies if there is one there. I'm not sure why disabling flat catalog would have changed anything regarding the JS.

**Comment by salvocolonna** [comment]
Exactly. Magento points to a table that not exists because is omitting prefix table, correct table name is mage_catalog_product_flat_1. I have still not found where correct this 'bug'...
This is the log:

exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'catalog_product_flat_1' doesn't exist' in /var/www/vhosts/domain.it/httpdocs/lib/Zend/Db/Statement/Pdo.php:228

**Comment by bobbyshaw** [comment]
Does your app/etc/local.xml file declare the table prefix?
