### ISSUE TITLE
Scripts within hole-punched EE FPC blocks are rendered out of order. 

### ISSUE THREAD

**Issue by bodiski** [bobbyshaw/magento-footer-js#3]
Hi,
I was wondering if you were able to get this working with EE FPC. I tested with a fresh install of mage EE 1.14.2.0 using RWD theme and the JS breaks on some product pages (e.g. /linen-blazer-538.html) where there's a block excluded from FPC that inserts some inline JS.

The only way I was able to fix this was by overwriting some FPC models (but that's ugly and I don't want to do it).
Somewhat related to this issue is this http://stackoverflow.com/questions/31211073/magento-events-including-http-response-send-before-not-launching-observer-with

Looking forward to hearing your opinion. Thanks.

![image](https://cloud.githubusercontent.com/assets/3490727/8635679/4abc9982-2828-11e5-9a9c-6fb464d91f3b.png)

![image](https://cloud.githubusercontent.com/assets/3490727/8635683/61d386a8-2828-11e5-93fc-6da60e4f7bbc.png)

**Comment by bobbyshaw** [comment]
Hi, I see the problem. That's not going to be trivial to solve for precisely the reason that you mention.  Initial thoughts suggest that it could be an observer on the PageCache controller which generates content for the dynamic blocks when FPC is enabled. 

I haven't opened editor to look into this yet but I will have a play over the next few weeks to see if I can find an alternative approach for FPC.

**Comment by bobbyshaw** [comment]
@bodiski Hi Andrei, new version of the extension for you to try out.  Tested with FPC enabled now.

**Comment by bodiski** [comment]
Hi Tom,
Thanks for the new release!
Unfortunately this is not fixed. Moreover it looks like the whole functionality (moving JS at the bottom) is now invalidated after the the 3rd page refresh of a cached page.

**Steps to reproduce:**
- Empty basket
- Go to `/linen-blazer-538.html`
- Add a White/Small product to basket
- Go back to the product page
- View the source code
- (with FPC enabled) Refresh the page 3 times. On the 4th refresh all JS is back in the default position.

_On the 4th page refresh_
![image](https://cloud.githubusercontent.com/assets/3490727/9425765/a196b9d2-4915-11e5-8655-d4b3da9b32b6.png)

**Comment by bobbyshaw** [comment]
Investigating.  Thanks for testing.

**Comment by bobbyshaw** [comment]
Thanks again for testing so quickly, my apologies for having missed this. Thanks also for the very thorough bug report 

After a couple of hours of searching for options, I've gone for an enterprise observer rewrite.  I don't know if it's the same one that you were originally suggesting or not.  I've tested again against CE and EE and made sure to refresh multiple times and trying with and without basket items and then adding to basket. 

The fix to test is on a new fpc branch if you do get a chance to test.  I'm going to talk to the meanbee team next week to get their thoughts as well.

**Comment by bodiski** [comment]
Thanks for updating the branch so quickly.
Everything seems in order now. I've tested with a few products and pages and I was able to checkout without any issues.
It might be worth investigating if there are any cases in default magento where a punched block re-generates some JS script with different/unique IDs in it, but I doubt there will be any. This branch might just be production ready :)

**Comment by bobbyshaw** [comment]
That's great, thanks.
