### ISSUE TITLE
script tags in HTML comments are not ignored

### ISSUE THREAD

**Issue by mzeis** [bobbyshaw/magento-footer-js#7]
Another extension used HTML comments in a .phtml template to not load the file:

```
<!--
<script type="text/javascript" src="http://domain.tld/some.js"></script>
-->
```

When activating Meanbee_Footerjs, the script tag was added to the end of the HTML code.

**Comment by bobbyshaw** [comment]
Well that's a shoddy way of doing it ;)  The regex here is going to need to be updated with that use case https://github.com/bobbyshaw/magento-footer-js/blob/master/app/code/community/Meanbee/Footerjs/Helper/Data.php#L6

**Comment by mkutyba** [comment]
Is it fixed?

**Comment by bobbyshaw** [comment]
No, I haven't worked on this edge case.

**Comment by bobbyshaw** [comment]
This is now in release v0.0.5
