### ISSUE TITLE
singleton/meanbee_footerjs/observer" already exists

### ISSUE THREAD

**Issue by jmailing** [bobbyshaw/magento-footer-js#8]
Sorry about my issue.
I had forgotten to turn compilation off.
Your extension rocks !!

Hello,

At first, thank you very much for this amazing extension.
I have installed it n my development server and it works well.
Full of coonfidence, I have made the same modman install (I'm a  newbee and I may have made a mistake) on my production server and thinkgs went not so smoothly :(
I have this error code "singleton/meanbee_footerjs/observer" already exists".
I don't understand the difference between the 2 environments.
What am I missing ?
Thanks again for your extension ! I was so glad to find it.

Julien

**Comment by bobbyshaw** [comment]
Hi @jmailing.  For historical reference for others, was this due to cache needing to be flushed?

**Comment by jmailing** [comment]
Hi,

Yes. As I have added in the beginning, the compilation must be off.
I am now looking to replace the javascripts call in the footer by their cdnjs (for instance) equivalent.
Hope I will understand the PHP code :)
Again, thank you for your extension !
