### ISSUE TITLE
Excluding specific assets

### ISSUE THREAD

**Issue by bennoislost** [bobbyshaw/magento-footer-js#9]
Hi Tom,

Just wondering if you had any thoughts on how exclude specific script tags from being moved to before body end?

My use case for this is Google Analytics trackers and Modernizr ideally should be left in the head..

I was thinking to modify the `Meanbee_Footerjs_Helper_Data::REGEX_JS` constant to exclude script tags which contain a data attribute (`mbfjs-exclude` ???)

Happy to submit a PR to enhance the module in the cleanest way possible :)

**Comment by bobbyshaw** [comment]
In general I think it's a good addition.  Do you think a data attribute or admin field like the merge js/css file exclusion?

**Comment by bennoislost** [comment]
Do you mean a field where this option can be enabled? I.E 

"Keep selected JavaScript in place" once "Move JavaScript to Footer" has been set yo yes?

**Comment by bobbyshaw** [comment]
Fooman speedster has a way for you to specify files that should be excluded.  I was thinking a field similar to this, e.g. "Exclude from moving to footer".

<img width="679" alt="screen shot 2015-10-06 at 08 03 41" src="https://cloud.githubusercontent.com/assets/553566/10302077/d7a8482a-6c00-11e5-924a-0058200d1432.png">

**Comment by philwinkle** [comment]
@bobbyshaw is this a feature you want or are exploring? Happy to pitch in, because we could use this ourselves at SD.

**Comment by bobbyshaw** [comment]
@philwinkle I think this would be a good feature.  I haven't been able to spend time on it myself though so you're welcome to.

**Comment by mkutyba** [comment]
Hello,
any news on that issue? I can't modify regex to achieve the expected result.

**Comment by bobbyshaw** [comment]
This is now available as part of [v0.0.4](https://github.com/bobbyshaw/magento-footer-js/releases/tag/v0.0.4) release
